In [25]:
import pandas as pd
import numpy as np

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,r2_score,mean_absolute_error
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor

In [2]:
df = pd.read_csv(r'/home/sakthi/milestone2.csv')

In [8]:
df.drop(columns=['SUBMISSION_DATE','DECISION_DATE'], inplace=True)

In [60]:
encode_df = pd.get_dummies(
    df,
    columns=[
        'VISA_CLASS',
        'PROCESSING_CENTER',
        'EMPLOYER_STATE',
        'WORKSITE_STATE',
        'PROCESSING_CENTER',
        'SERVICE_OFFICE'
    ],
    drop_first=True
)

In [61]:
encode_df.head()

,APPLICATION_ID,APPLICATION_STATUS,SOC_CODE,SOC_TITLE,JOB_TITLE,EMPLOYER_NAME,WORKSITE_CITY,WAGE_RATE_OF_PAY_FROM,WAGE_RATE_OF_PAY_TO,PREVAILING_WAGE,...,WORKSITE_STATE_VA,WORKSITE_STATE_VI,WORKSITE_STATE_VT,WORKSITE_STATE_WA,WORKSITE_STATE_WI,WORKSITE_STATE_WV,WORKSITE_STATE_WY,PROCESSING_CENTER_New York Service Center,PROCESSING_CENTER_Texas Service Center,SERVICE_OFFICE_WASHINGTON DC
0,I-200-24087-834912,Certified,17-2051.00,Civil Engineers,Engineer,"Arup US, Inc.",Los Angeles,72322.0,93000.00,72322.0,...,False,False,False,False,False,False,False,False,False,True
1,I-200-24150-046162,Certified,15-1296.00,"Software Developers, R&D","Manager, IT Applications - Research",The Jackson Laboratory,Sacramento,107162.0,162310.00,107162.0,...,False,False,False,False,False,False,False,False,False,True
2,I-200-20316-908390,Certified,15-1141.00,Database Administrators,DATABASE ADMINISTRATOR,SREE INFOTECH LLC,Torrance,116147.0,116160.00,116147.0,...,False,False,False,False,False,False,False,False,False,True
3,I-200-23272-400930,Certified,15-1252.00,Software Developers,Senior Member of Technical Staff,"Nutanix, Inc.",San Jose,204600.0,282000.00,204600.0,...,False,False,False,False,False,False,False,False,False,True
4,I-200-21292-654992,Certified,13-2099.01,Financial Quantitative Analysts,Vice President / Sr Quantitative Fin Analyst,BANK OF AMERICA N.A.,Atlanta,180000.0,180000.01,111280.0,...,False,False,False,False,False,False,False,False,False,True

In [62]:
encode_df.drop(columns=[
    'APPLICATION_ID',
    'JOB_TITLE',
    'EMPLOYER_NAME',
    'SOC_TITLE'
], inplace=True)

In [63]:
y = df['PROCESSING_DAYS']

In [64]:
encode_df.drop(df['PROCESSING_DAYS'])

,APPLICATION_STATUS,SOC_CODE,WORKSITE_CITY,WAGE_RATE_OF_PAY_FROM,WAGE_RATE_OF_PAY_TO,PREVAILING_WAGE,PW_WAGE_LEVEL,NEW_EMPLOYMENT,CHANGE_EMPLOYER,AMENDED_PETITION,...,WORKSITE_STATE_VA,WORKSITE_STATE_VI,WORKSITE_STATE_VT,WORKSITE_STATE_WA,WORKSITE_STATE_WI,WORKSITE_STATE_WV,WORKSITE_STATE_WY,PROCESSING_CENTER_New York Service Center,PROCESSING_CENTER_Texas Service Center,SERVICE_OFFICE_WASHINGTON DC
0,Certified,17-2051.00,Los Angeles,72322.0,93000.0,72322.0,1.0,1,0,0,...,False,False,False,False,False,False,False,False,False,True
13,Certified,29-1229,Oak Ridge,125.0,160.0,115.0,2.0,1,0,0,...,False,False,False,False,False,False,False,False,False,True
14,Certified,15-1132.00,West Melbourne,119350.0,119351.0,92622.0,2.0,0,1,0,...,False,False,False,False,False,False,False,False,False,True
15,Certified,15-1199.09,Kalamazoo,48693.0,60000.0,48693.0,1.0,1,0,0,...,False,False,False,False,False,False,False,False,True,True
16,Certified,15-1132.00,Westland,112736.0,144720.0,112736.0,4.0,0,1,0,...,False,False,False,False,False,False,False,False,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,Certified,15-1252.00,Wesley Chapel,85613.0,85620.0,85613.0,2.0,0,1,0,...,False,False,False,False,False,False,False,False,True,True
14996,Certified,13-1041.07,San Francisco,116355.0,135000.0,116355.0,4.0,0,1,0,...,False,False,False,False,False,False,False,False,False,True
14997,Certified,15-1199.09,Silver Spring,121722.0,141356.0,121722.0,3.0,0,0,1,...,False,False,False,False,False,False,False,True,False,True
14998,Certified,11-3021.00,SANTA CLARA,198814.0,212425.0,198814.0,2.0,0,0,0,...,False,False,False,False,False,False,False,False,False,True
14999,Certified,17-2131.00,Phoenix,134950.0,150800.0,121597.0,4.0,0,0,0,...,False,False,False,False,False,False,False,False,False,True

In [65]:
features = [
'WAGE_RATE_OF_PAY_FROM',
'WAGE_RATE_OF_PAY_TO',
'PREVAILING_WAGE',
'PW_WAGE_LEVEL',
'NEW_EMPLOYMENT',
'CHANGE_EMPLOYER',
'AMENDED_PETITION',
 'APPLICATION_MONTH',
'SUBMISSION_YEAR',
'SUBMISSION_MONTH',
'SUBMISSION_DAY',
'SUBMISSION_QUARTER'
]

In [92]:
x = encode_df.drop(columns=[
'APPLICATION_STATUS',
    "SOC_CODE",
    "WORKSITE_CITY",
    "PROCESSING_DAYS"

])

In [93]:
print(x)

       WAGE_RATE_OF_PAY_FROM  WAGE_RATE_OF_PAY_TO  PREVAILING_WAGE  \
0                    72322.0             93000.00          72322.0
1                   107162.0            162310.00         107162.0
2                   116147.0            116160.00         116147.0
3                   204600.0            282000.00         204600.0
4                   180000.0            180000.01         111280.0
...                      ...                  ...              ...
14995                85613.0             85620.00          85613.0
14996               116355.0            135000.00         116355.0
14997               121722.0            141356.00         121722.0
14998               198814.0            212425.00         198814.0
14999               134950.0            150800.00         121597.0

       PW_WAGE_LEVEL  NEW_EMPLOYMENT  CHANGE_EMPLOYER  AMENDED_PETITION  \
0                1.0               1                0                 0
1                4.0               0                0                 1
2                2.0               0                0                 0
3                2.0               0                0                 0
4                4.0               0                1                 0
...              ...             ...              ...               ...
14995            2.0               0                1                 0
14996            4.0               0                1                 0
14997            3.0               0                0                 1
14998            2.0               0                0                 0
14999            4.0               0                0                 0

       APPLICATION_MONTH  APPLICATION_DAYS  SUBMISSION_YEAR  ...  \
0                      3                27             2024  ...
1                      5                29             2024  ...
2                     11                11             2020  ...
3                      9                29             2023  ...
4                     10                19             2021  ...
...                  ...               ...              ...  ...
14995                  3                21             2023  ...
14996                  7                23             2021  ...
14997                 11                12             2021  ...
14998                  7                 2             2021  ...
14999                  2                 4             2023  ...

       WORKSITE_STATE_VA  WORKSITE_STATE_VI  WORKSITE_STATE_VT  \
0                  False              False              False
1                  False              False              False
2                  False              False              False
3                  False              False              False
4                  False              False              False
...                  ...                ...                ...
14995              False              False              False
14996              False              False              False
14997              False              False              False
14998              False              False              False
14999              False              False              False

       WORKSITE_STATE_WA  WORKSITE_STATE_WI  WORKSITE_STATE_WV  \
0                  False              False              False
1                  False              False              False
2                  False              False              False
3                  False              False              False
4                  False              False              False
...                  ...                ...                ...
14995              False              False              False
14996              False              False              False
14997              False              False              False
14998              False              False              False
14999              False              False              False

       WORKSITE_STATE_WY  PROCESSING_CENTER_New York Service Center  \
0                  False                                      False
1                  False                                      False
2                  False                                      False
3                  False                                      False
4                  False                                      False
...                  ...                                        ...
14995              False                                      False
14996              False                                      False
14997              False                                       True
14998              False                                      False
14999              False                                      False

       PROCESSING_CENTER_Texas Service Center  SERVICE_OFFICE_WASHINGTON DC
0                                       False                          True
1                                       False                          True
2                                       False                          True
3                                       False                          True
4                                       False                          True
...                                       ...                           ...
14995                                    True                          True
14996                                   False                          True
14997                                   False                          True
14998                                   False                          True
14999                                   False                          True

[15000 rows x 129 columns]

In [94]:
x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42
)

In [95]:
def evaluate(y_true, y_pred):
    print("MAE:", mean_absolute_error(y_true, y_pred))
    print("RMSE:", np.sqrt(mean_squared_error(y_true, y_pred)))
    print("R2:", r2_score(y_true, y_pred))

In [96]:
model = LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [105]:
y_pred = model.predict(x_test)

In [106]:
evaluate(y_test,y_pred)

MAE: 0.4548234103457742
RMSE: 0.8272713640045222
R2: 0.022853306611940516

In [107]:

rf = RandomForestRegressor(random_state=42)
rf.fit(x_train, y_train)

y_pred_rf = rf.predict(x_test)

In [108]:


gb = GradientBoostingRegressor(random_state=42)
gb.fit(x_train, y_train)

y_pred_gb = gb.predict(x_test)

In [109]:
evaluate(y_test, y_pred_rf)

MAE: 0.16718333333333327
RMSE: 0.4973187106876233
R2: 0.6468710021930827

In [110]:
evaluate(y_test, y_pred_gb)

MAE: 0.33789045935918705
RMSE: 0.7153141266470525
R2: 0.2694374803238858

In [111]:
results = pd.DataFrame({
    "Model": ["Linear Regression", "Random Forest", "Gradient Boosting"],
    "MAE": [
        mean_absolute_error(y_test, y_pred),
        mean_absolute_error(y_test, y_pred_rf),
        mean_absolute_error(y_test, y_pred_gb)
    ],
    "RMSE": [
        np.sqrt(mean_squared_error(y_test, y_pred)),
        np.sqrt(mean_squared_error(y_test, y_pred_rf)),
        np.sqrt(mean_squared_error(y_test, y_pred_gb))
    ],
    "R2 Score": [
        r2_score(y_test, y_pred),
        r2_score(y_test, y_pred_rf),
        r2_score(y_test, y_pred_gb)
    ]
})

In [112]:
results

               Model       MAE      RMSE  R2 Score
0  Linear Regression  0.454823  0.827271  0.022853
1      Random Forest  0.167183  0.497319  0.646871
2  Gradient Boosting  0.337890  0.715314  0.269437

### Since Random forest have higher R2 we choose Random Forest for hyper tuning

## hyper tuning

In [113]:
param_grid = {
    'n_estimators': [100, 200],
    'max_depth': [10, 20, None],
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2],
    'max_features': ['sqrt', 'log2']
}

In [114]:
grid_search = GridSearchCV(
    estimator=rf,
    param_grid=param_grid,
    cv=3,
    scoring='r2',
    n_jobs=-1
)

grid_search.fit(x_train, y_train)

GridSearchCV(cv=3, estimator=RandomForestRegressor(random_state=42), n_jobs=-1,
             param_grid={'max_depth': [10, 20, None],
                         'max_features': ['sqrt', 'log2'],
                         'min_samples_leaf': [1, 2],
                         'min_samples_split': [2, 5],
                         'n_estimators': [100, 200]},
             scoring='r2')

In [115]:
print(grid_search.best_params_)

{'max_depth': None, 'max_features': 'sqrt', 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 200}

In [116]:
best_rf = grid_search.best_estimator_

In [117]:
y_pred_brf = best_rf.predict(x_test)

In [118]:
evaluate(y_test,y_pred_brf)

MAE: 0.279605
RMSE: 0.6453168536979851
R2: 0.40542068113111285

### hyper tuning worsens the model performance so i am choosing the default parameters for the random forest model

In [119]:
import joblib

joblib.dump(rf, "visa_processing_model.pkl")

['visa_processing_model.pkl']